name: My Test

on:
  push
    # Sequence of patterns matched against refs/tags
    #tags:
      #- 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.x, 8.x, 9.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx danger ci
      
      - name:  Compile JS
      - run: npm run compile

      - name: Build all examples
      - run: npm run build:basic
      - run: npm run build:customised
      - run: npm run build:sections

    