name: My Test

on:
  push
    # Sequence of patterns matched against refs/tags
    #tags:
      #- 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Check npm version
        id: check_npm
        run: |
          OUTPUT=$(npm -v)
          npm -v

      # - name: Update npm
      #   if: ${{ steps.check_npm.outputs.OUTPUT }} != 5.7*
      #   run: |
      #     npm install -g npm@'>=5.7.1'

      - name:  Compile JS
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          npx ci
          npm run compile

      - name: Build all examples
        run: | 
          npm run build:basic
          npm run build:customised
          npm run build:sections
      
      - name: Run cypress pre
        run: | 
          npm run test:cypress:pre
      
      - name: Run cypress start server
        run: | 
          npm run test:cypress:startServer & npm run test:cypress:startServer:post
      
      - name: Run cypress run
        run: | 
          npm run test:cypress:run

          
    